
transformation_type_paths:
  similar_shape_dict: "data/similar_shape_dict.json"
  shape_confusion_dict: "data/shape_confusion_dict.json"
  similar_consonant_dict: "data/similar_consonant_dict.json"
  similar_vowel_dict: "data/similar_vowel_dict.json"
  pinyin_distance_matrix: "data/pinyin_distance_matrix.pkl"
  prone_to_confusion_dict: "data/prone_to_confusion_dict.json"

n_beam: 8
n_beam_hyps_to_keep: 1
n_observed_chars: 8
alpha: 2.5
temperature: 1.0
distortion_model_smoothing: -15.0
use_faithfulness_reward: true
max_length: 128

distortion_probs:
  IDT: -0.04
  PTC: -2.50
  SAP: -3.75
  SIP: -4.85
  SIS: -5.40
  OTP: -8.91
  OTS: -8.91
  UNR: -14.99

distortion_type_prior_priority:
  - IDT
  - PTC
  - SAP
  - SIP
  - SIS
  - OTP
  - OTS
  - UNR

distortion_type_prior_priority_order:
  - PTC
  - SAP
  - SIP
  - SIS
  - OTP
  - OTS
