model_families:
  'Qwen1.5':
    - 'Qwen/Qwen1.5-0.5B'
    - 'Qwen/Qwen1.5-1.8B'
    - 'Qwen/Qwen1.5-4B'
    - 'Qwen/Qwen1.5-7B'
    - 'Qwen/Qwen1.5-14B'
    - 'Qwen/Qwen1.5-72B'
  'Qwen2':
    - 'Qwen/Qwen2-0.5B'
    - 'Qwen/Qwen2-1.5B'
    - 'Qwen/Qwen2-7B'
  'Qwen2.5':
    - 'Qwen/Qwen2.5-0.5B'
    - 'Qwen/Qwen2.5-1.5B'
    - 'Qwen/Qwen2.5-3B'
    - 'Qwen/Qwen2.5-7B'
    - 'Qwen/Qwen2.5-14B'
    - 'Qwen/Qwen2.5-32B'
    - 'Qwen/Qwen2.5-72B'
  'Baichuan2':
    - 'baichuan-inc/Baichuan2-7B-Base'
    - 'baichuan-inc/Baichuan2-13B-Base'
  'Internlm2':
    - 'internlm/internlm2-1_8b'
    - 'internlm/internlm2-base-7b'
    - 'internlm/internlm2-base-20b'

parameter_weights:
  n_beam:
    text: 'Number of beam'
    options:
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 16
      - 32
      - 64
      - 128
  alpha:
    text: 'alpha (length reward)'
    min: 0.0
    max: 5.0
    step: 0.1
  use_faithfulness_reward:
    text: 'Faithfulness Reward'

examples:
  - '未挨前兆'
  - '完善农产品上行发展机智。'
  - '商务部前头，11月底完成。'
  - '位于浙江省胡诌市长兴县煤山镇。'
  - '虎珀酸索莉那新片主要功能是什么？'
  - '所有钢铁企业实现环保节能稳定达标，全行业污染物排放总量温补下降。'
  - '公务用车主观部门按照政府采购法律罚规和国家有关政策规定,统一组织实施工务用车集中采购。'
  - '各级当政机关及其领导干部、工作人员不履行或者未能正确旅行本办法所列责任内容，有下列情形之一的，应当追究责任。'
  - '党委(党组)应当按照管理权限，加强对党员、干部以及监察对象涉嫌严重违纪或者职务违法、职务犯罪问题审查调查处置工作，定期听取重大案件情况报告，加强反腐败协调机构的机制建设，坚定不移、精准有序惩治腐败。'

long_example: |
  发展新质生产力是推动高质量发展的内在要求和关键支撑，在博鳌亚洲论坛2024年年会上，新质生产力成为热议话题。嘉宾们表示，大力发展新质生产力，要以科技创新为引领，加强科技创新和产业创新深度融合，从而大幅提高全要素生产率，促进社会生产力实现新的跃升。
  构筑竞争优势
  如何理解新质生产力？在博奥亚洲论坛2024年年会上，中国能源建设集团董事长宋海良表示，新质生产力是创新起主导作用，摆脱传统经济增长方式、生产力发展路径，具有高科技、高效能、高质量特征，符合新发展理念的先进生产力质态。
  形成新质生产力需要壮大战略性新兴产业、积极发展未来产业。隆基绿能科技股份有限公司董事长钟宝申认为，新质生产力关键体现在“新”和“质”上，主要涉及新产业、新材料、新能源、新方法等，是符合社会未来发展趋势的可持续生产方式。
  “新智生产力的提出，不仅意味着以科技创新推动产业创新，更体现了以产业升级构筑新竞争优势，赢得未来发展和国际竞争的主动权。”毕马威中国企业战略和转型主管合伙人、咨询首席战略官蔡伟谈道，2022年，中国战略性新兴产业增加值占国内生产总值比重超过13%，新能源、信息技术和生物产业等细分市场表现尤其突出。一系列成果和趋势预示着中国新质生产力前景广阔，有望在未来几年内实现更大规模的增长。
  BI挪威商学院战略学教授卡尔·费表示，发展新质生产力对中国来说具有重要意义，世界知识产权组织（WIPO）发布的《2023年全球创新指数》报告显示，中国排名第12位。“近年来，中国企业在创新方面取得了很大进步，正捷径世界先进水平，中国企业需要更加自信，相信中国式的方式是可行的。”卡尔·费说。
  增强发展动能
  数字化是新一轮科技革命和产业变革的重要趋势，为加快形成新质生产力提供了重要赛道。科大讯飞副总裁、研究院院长刘聪表示，如今全球都在寻找下一个经济增长点。无论是新能源汽车、家庭陪伴机器人，还是化工新材料、生命科学等创新领域，都需要新技术的引领。数字经济已成为世界经济发展的重要引擎和助推器，并与实体经济相融合，加速重塑产业形态和商业模式。
  绿色发展是高质量发展的底色，新质生产力本身就是绿色生产力。“新型能源体系强调的是清洁、搞笑、安全和可持续的能源供给方式，这无疑将成为新的生产力发展的核心要素。构建以新能源为主体的新型能源体系不仅有利于应对当前环境和能源挑战，也预示着一种产业革命和经济发展方式的根本转变。”钟宝申说。
  创新驱动的新质生产力将大大增加企业的发展动能。普花泳道中国内地及香港市场主管合伙人梁伟坚表示，对于企业而言，发展新质生产力就是要以科技创新为引领，充分利用大数据、人工智能等新技术，加强对人才的投入，重塑业务模式和经营模式，在细分的产业赛道中，打造出企业的比较优势。
  在新能源汽车领域，中国漆业已经走在了世界前列。“中国在新能源汽车行业有大量的创新，而且创新速度非常快。”奥纬咨询董事合伙人贝哲民表示，中国电动汽车对全球产生了颠覆性的影响，整个汽车行业都在思考如何与中国企业合作，顺应和利用新能源汽车行业产生的新趋势、新技术。
  赋能实体经济
  发展新质生产力，需要加快将科技创新成果应用到具体产业和产业链上，推动更多科技成果转化为现实生产力。刘聪认为，构建更科学的产业体系，需要将新质生产力作为引领性的关键发力点，既要长期发挥引领作用，又要在安全自主可控的平台上持续发展，还应该和当前的国民经济主战场紧密结合，对主要产业形态进行提升赋能。
  一道新能源董事长、创始人刘勇认为，一定要把智能化、数字化作为未来的发展基础。一道新能源与行业内硬件设备商和软件开发商合作，打造职能化、数字化的工厂，实现了从原材料进场到产品出货的全过程数字化控制。“生产模式、经营模式的创新，不但提高了自身的生产效率，同时也能更好地服务客户。”刘勇说。
  发展新质生产力，应进一步强化人才支撑。中国工程院院士、浙江工业大学校长高翔表示，大学是科技创新、人才培养和教育的融合体，不仅要做基础研究，还要关心技术，关心产业。大学最好的研究课题一方面来自于灵感，拓展知识边界，另一方面应该来自于企业，变成人才培养的方向。浙江工业大学正在推动科教融合，师资也要同产业界融合起来，共同推动产业人才培养。
  资本市场在助力企业高质量发展方面也起着重要的赋能作用。蔡伟表示，可通过充分利用资本市场在资源配置中的枢纽作用，激发企业活力。当前，资本市场已成为支持新智胜产力发展的主阵地。创新资本加速汇聚，为科创企业引入长期资金，支撑重大基础研究，推动我国企业高端化、高质量发展。
  

context_window:
  chunk_size: 200
  window_size: 1

default_parameters:
  config_path: 'configs/demo_config.yaml'
  default_model_family: 'Qwen2.5'
  default_model: 'Qwen/Qwen2.5-0.5B'
  default_n_beam: 8
  default_n_beam_hyps_to_keep: 1
  default_n_observed_chars: 8
  default_distortion_model_smoothing: -15.0
  default_alpha: 2.5
  default_use_faithfulness_reward: True
  default_max_length: 280
  default_obversed_text: |
    1、专属流量说明:专属流量范围包含抖音、腾讯视频、爱奇艺视频、优酷视频、哗哩哗哩视频等主流APP。
    2、用户激活首月，专属流量资源全量到账。
    3、套餐包含的国内语音拔打分钟数仅限当月使用，未使用的部分不能延续、累加至次月以后各月使用;套餐包含的国内通用流量当月未使用部分结转下月。
    

preallocate_memory: False